server:
  port: ${port:8080}
spring:
  profiles:
    active:  default
  session:
    store-type: hash_map
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:SAMPLES;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    name: SAMPLES
    username: sa
    password:
    validationQuery: SELECT 1
    platform: h2
    initialize: true
    schema: classpath:/schema-h2.sql
    data: classpath:/data-h2.sql
  jackson:
    serialization-inclusion: non_nul
    serialization.indent_output: true

  data:
    mongodb:
      host: 192.168.30.198
      port: 27017
      database: SAMPLES
# H2 Web Console
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: info
    org.springframework: info
    org.chiwooplatform.samples: debug

---
spring:
  profiles: dev

logging:
  config: classpath:logback-dev.xml

server:
  port: ${port:8082}}